apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
strategy:
   type:RollingUpdate 
   rollingUpdate:
      maxUnavailable: 1  #How many POD max unavailable. one POD cannot be available
      maxSurge: 1 #create pods with series
minReadySeconds: 60 #wait before terminate another pod
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
